package vn.com.ocb.aipdmaservice.enumDefine;

public enum  AuthenticationInCorrectReason {
    TOKEN_INCORRECT,
    TOKEN_EXPIRED,
    INACTIVE_SMS_AUTHENTICATION_METHOD,
    INVALID_BIRTH_DATE,
    INVALID_BIRTH_DATE_CHANNEL_BLOCKED,
    CREDENTIAL_INCORRECT,
    BLOCKED_CONTEXT,
    LIST_NOT_ACTIVE,
    TOKEN_ID_INCORRECT,
    INCORRECT_AND_BLOCKED,
    LAST_ON_LIST,
    OUTDATED_MIGRATION,
    PROCESSING_ERROR,
    PASSWORD_MAX_LENGTH_ERROR,
    PASSWORD_MIN_LENGTH_ERROR,
    INCORRECT_SMS_AND_BLOCKED,
    WWW_CHANNEL_BLOCKED,
    USER_STATUS_IN_CHANGE;
}
